import Head from "next/head";
import * as THREE from "three";
import Router from "next/router";
import React, { useContext, useEffect, useState } from "react";
import Scene from "../components/Scene";
import Resizable from "../components/tutorialHelpers/Resizable";
import Prerequisites from "../components/tutorialSteps/Prerequisites";
import AppContext from "../contexts/AppContextProvider";
import Box, { boxSceneFunction } from "../components/tutorialSteps/Box";
import Renderer, {
  rendererSceneFunction,
} from "../components/tutorialSteps/Renderer";
import Loader, {
  loaderSceneFunction,
} from "../components/tutorialSteps/Loader";
import Spin, { spinSceneFunction } from "../components/tutorialSteps/Spin";
import Raycaster, {
  raycasterSceneFunction,
} from "../components/tutorialSteps/Raycaster";
import CameraAnimation, {
  cameraAnimationSceneFunction,
} from "../components/tutorialSteps/CameraAnimation";
import InfoBubble, {
  infoBubbleSceneFunction,
} from "../components/tutorialSteps/InfoBubble";
import CameraAnimationOld, {
  cameraAnimationOldSceneFunction,
} from "../components/tutorialSteps/CameraAnimationOld";
type StepList = Array<{
  id: string;
  element: any;
  pageFunction?: any;
}>;
export const stepList: StepList = [
  {
    id: "prerequisites",
    element: <Prerequisites></Prerequisites>,
  },
  {
    id: "renderer",
    element: <Renderer></Renderer>,
    pageFunction: rendererSceneFunction,
  },
  {
    id: "box",
    element: <Box></Box>,
    pageFunction: boxSceneFunction,
  },
  {
    id: "loader",
    element: <Loader></Loader>,
    pageFunction: loaderSceneFunction,
  },
  {
    id: "spin",
    element: <Spin></Spin>,
    pageFunction: spinSceneFunction,
  },
  {
    id: "raycaster",
    element: <Raycaster></Raycaster>,
    pageFunction: raycasterSceneFunction,
  },
  {
    id: "cameraAnimation",
    element: <CameraAnimation></CameraAnimation>,
    pageFunction: cameraAnimationSceneFunction,
  },
  {
    id: "cameraAnimationOld",
    element: <CameraAnimationOld></CameraAnimationOld>,
    pageFunction: cameraAnimationOldSceneFunction,
  },
  {
    id: "infoBubble",
    element: <InfoBubble></InfoBubble>,
    pageFunction: infoBubbleSceneFunction,
  },
];
const Tutorial = () => {
  const [stepIndex, setStepIndex] = useState<number>(-1);

  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => {
    const routerStepIndex = stepList.findIndex(
      (item) => item.id === Router.query.step
    );

    if (routerStepIndex !== stepIndex) setStepIndex(routerStepIndex);
  });
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen max-h-screen flex flex-row">
        <Resizable>
          {stepList[stepIndex] && stepList[stepIndex].element}
          {!stepList[stepIndex] && "Step does not exist"}
        </Resizable>
        {stepList[stepIndex] && stepList[stepIndex].pageFunction && (
          <Scene threeScript={stepList[stepIndex].pageFunction}></Scene>
        )}
      </div>
    </>
  );
};

export default Tutorial;
